### ISSUE TITLE
Migrate from es-interface/[taxonomy] to Tag Facets API

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-tme-search-api#37]
read [the docs](https://github.com/Financial-Times/next-tag-facets-api/blob/master/README.md)! CC @matthew-andrews

**Comment by i-like-robots** [comment]
Please also see this issue as there may be changes to the API: https://github.com/Financial-Times/next-tag-facets-api/issues/13

**Comment by wheresrhys** [comment]
Been thinking that maybe the best approach to handling the 'looking for' items is to add them to the index in ES, then we can get rid of this middle-man app entirely

**Comment by matthew-andrews** [comment]
yeah that could work, we would need to be careful about how we model them though.

**Comment by i-like-robots** [comment]
We have a the `searchLabel` field in ES... is that sort of what we want?

**Comment by matthew-andrews** [comment]
i mean…… would these things be effectively like articles?

**Comment by andygout** [comment]
I'm looking into this now... it seems like there is little reason to use this app over using the tag facets API directly? Is there any particular data manipulation we need to perform that the facets API doesn't have which would warrant having an intermediary API to perform such tasks?

**Comment by wheresrhys** [comment]
2 use cases I can think of

- Brexit doesn't exist as a metadata tag, so isn't in tag facets API. This app has the ability to create synonyms
- searching for bits of the site that aren't content e.g. My Account. 

I think deciding on a way to get these into elastic search is better than keeping a separate app in the long run

**Comment by andygout** [comment]
Do we have an idea of how many non-content bits of the site there are to be accounted for (i.e. Markets Data; Portfolio; My Account, etc.)? Maybe Guy Valerio is the person to get that from?

Is it possible that this handling could be done in [`n-header-footer/header/typeahead.js`](https://github.com/Financial-Times/n-header-footer/blob/master/header/typeahead.js), or better to separate entirely into separate API?

**Comment by wheresrhys** [comment]
This'll give you an idea of the current state of things https://docs.google.com/spreadsheets/d/1rHuBdwKLGMs0azyDdyrKbLEesBbKS9TVJVPCwD83LX4/edit#gid=0. It's not many things, but arguably some are important to have in search
